#!/usr/bin/env bash



# bump the version
cd projects/ngx-sign-in-redirect
VERSION="$(npm version patch)"
cd ../..

# build the lib
ng build ngx-sign-in-redirect
cp README.md LICENSE dist/ngx-sign-in-redirect/

# build the demo
ng build ngx-sign-in-redirect-demo  --prod --aot --baseHref /ngx-sign-in-redirect/

# build the docs
compodoc  -p projects/ngx-sign-in-redirect/tsconfig.lib.json  --disableCoverage --output docs/docs




# publish to NPM
cd dist/ngx-sign-in-redirect
npm publish --access public
cd ../..


# commit with tag
git add -A
git commit -m "published version ${VERSION} to npm"
git tag  $VERSION
git push
git push --tags
